type User @table {
  userId: UUID!
  createdAt: Timestamp!
  displayName: String
  email: String
}

type Birthday @table {
  personName: String!
  birthDate: Date!
  createdAt: Timestamp!
  yearOfBirth: Int
  notes: String
  isPublic: Boolean
  user: User
}

type Reminder @table {
  reminderDate: Timestamp!
  createdAt: Timestamp!
  sent: Boolean!
  message: String
  birthday: Birthday
}

type Tag @table {
  tagName: String!
  createdAt: Timestamp!
  description: String
}

type BirthdayTag @table(key: ["birthday", "tag"]) {
  birthday: Birthday!
  tag: Tag!
  createdAt: Timestamp
}